frase = 'Curso em Vídeo Phyton'
# Análises!
x = len(frase)
y = frase.count('o',0,)
z = frase.find('deo')
w = 'Curso' in frase
# Transformações!
c = frase.upper()
b = frase.lower()
k = frase.capitalize()
l = frase.title()
h = frase.strip()
f = frase.rstrip()
j = frase.lstrip()
i = '-'.join(frase.split())
g = frase.split()
v = frase.replace('Phyton','Android',)
print('O tamanho da frase é {}'.format(x))
print('A quantidade de "o"s é {}'.format(y))
print('"deo" começa em {}'.format(z))
print('Há "Curso" em frase? {}'.format(w))
print(c)
print(b)
print(k)
print(l)
print(h)
print(f)
print(j)
print(g[2])
print(i)
print(v)
c = input('pressione Enter para fechar!')
